### ISSUE TITLE
汉语输入法与自动补全系统BUG

### ISSUE THREAD

**Issue by SPTAU** [thebaselab/codeapp#58] opened 2021-03-22 11:43 UTC
在使用汉语输入法时，输入已存在某些变量名，再按空格，会自动再输入一次该变量。而使用英语输入法则不会触发。
例如：
已输入 line 作为变量
在汉语输入法下输入line，会出现自动补全的候选框
按下空格后，会先自动填充该候选项，再加一个空格
![BE7B850D-F0A7-49B1-B45A-BB97784A7F7D](https://user-images.githubusercontent.com/46211051/111984874-e4f27a80-8b46-11eb-8e9d-c317bd9bbb6b.jpeg)
按下回车
![2AC30EC4-4692-4746-8444-E93EB0D08C4C](https://user-images.githubusercontent.com/46211051/111984881-e754d480-8b46-11eb-809f-9f91575886f2.jpeg)
按下空格
![3527149D-098A-4B2E-BB7A-E6A8149545C0](https://user-images.githubusercontent.com/46211051/111984886-e7ed6b00-8b46-11eb-88a4-ccc7945f984d.jpeg)

**Comment by bummoblizard** [comment] 2021-03-22 12:41
I can reproduce it. Looks like it's related to Monaco Editor. I will see what I can do.

**Comment by SPTAU** [comment] 2021-03-22 13:39
> I can reproduce it. Looks like it's related to Monaco Editor. I will see what I can do.

And there is another problem. The bottom border of the terminal seems to be so low that it is difficult for me to see it.
![A0DA546F-CC0D-47B0-A34F-C4F0DF0560AA](https://user-images.githubusercontent.com/46211051/111998091-a49af880-8b56-11eb-9add-7818084768af.jpeg)
You can see that "Document $" has been partially obscured.
I once posted it in another post, but I'm not sure if you have seen it.

**Comment by bummoblizard** [comment] 2021-03-22 13:41
Ah yes I saw that. I will fix it in the next update. As a workaround, you may clear the terminal by tapping the square button or using command-k.

**Comment by bummoblizard** [comment] 2021-03-22 14:25
Is there any particular reason you closed this? If not I am reopening it.

Filed an issue on vscode: https://github.com/microsoft/vscode/issues/119469

**Comment by SPTAU** [comment] 2021-03-22 15:26
> Is there any particular reason you closed this? If not I am reopening it.
> 
> Filed an issue on vscode: [microsoft/vscode#119469](https://github.com/microsoft/vscode/issues/119469)

Emmm, I just thought "close" means that the feedback is over

**Closed** 2022-05-29 14:35 UTC
Labels: bug, upstream
