### ISSUE TITLE
Editor doesn't support touch controls

### ISSUE THREAD

**Issue by James-lx** [thebaselab/codeapp#169] opened 2021-06-29 06:29 UTC
It's hard to code using iPad virtual keyboard,and it doesn't support selecting using either hand or keyboard but sometimes it can do, I don't know why.

**Comment by bummoblizard** [comment] 2021-06-30 06:54
Thank you for the message. This is a known issue from the very beginning. We use [monaco-editor](https://github.com/microsoft/monaco-editor), which is the core editor from VS Code. While this gives us great performance, syntax highlighting and other features that VS Code users are familiar with, the editing experience without a hardware keyboard is poor.

I am attempting to patch monaco-editor to support touch controls, but it won't be easy. I am also considering to let users opting for an less powerful, but touch-friendly editor like [CodeMirror 6](https://codemirror.net/6/).

**Comment by James-lx** [comment] 2021-06-30 09:34
Thank you for your prompt reply 
Did you mean I can have better experience using hardware keyboard? But I can't use mouse(without keyboard)to select or others either.

**Comment by bummoblizard** [comment] 2021-06-30 09:35
Yes. You can select text in the latest build: https://testflight.apple.com/join/EgZ8sE2P

It will be released to the App Store in a few days.

**Comment by vwkd** [comment] 2022-05-20 12:42
Currently Code is unusable with virtual keyboard due to selection not working. 

CodeMirror 6 seems to support this fine. An entire replacement of Monaco or at least an option would be appreciated.

**Comment by bummoblizard** [comment] 2022-05-20 22:18
> Currently Code is unusable with virtual keyboard due to selection not working.
> 
> CodeMirror 6 seems to support this fine. An entire replacement of Monaco or at least an option would be appreciated.

Yes and I've thought about it. The issue is that CodeMirror doesn't provide many features that are tightly integrated to Code App and maintaining two sets of editor in one app seems troublesome. If you would like to see native controls and a more lightweight editor Runestone Editor does it really well (https://github.com/simonbs/Runestone).

I'm still open to this idea though.

**Comment by bummoblizard** [comment] 2022-11-27 10:53
@benwu030 It's time to revisit this. Besides CodeMirror, Runestone is also a nice candidate for this: https://github.com/simonbs/Runestone. My plan is to support both Monaco Editor and the new editor. Now that we've completed the refactoring of the codebase this should not be too troublesome to implement.

We might need to give up certain feature like diff editors and searching though.

**Comment by Lukas-Batema** [comment] 2022-12-01 14:36
I use diff and searching pretty frequently, and would not like this to be removed :(

**Comment by bummoblizard** [comment] 2022-12-10 11:34
> I use diff and searching pretty frequently, and would not like this to be removed :(

We will keep both editors :)

**Comment by redscorpse** [comment] 2023-02-05 21:36
I find this issue with text selection annoying too, and I would like to suggest adding something like in [Online GDB](https://www.onlinegdb.com). It uses the Ace editor (which I don't know if has the same issue as Monaco) but adds to the left column of line numbers the ability of folding and selecting multiple lines.

![Select-text-with-column](https://user-images.githubusercontent.com/73442486/216847420-78dffb8e-116c-4226-9545-714346a25b37.jpg)

**Comment by jbschooley** [comment] 2023-04-09 20:14
If you're able to patch monaco-editor to support touch, would you consider upsteaming it? This app is great, but I sometimes use VS Code in safari and on my windows tablet, and touch doesn’t work there either. Fixing that would be incredible.

**Comment by SRUKen** [comment] 2023-12-10 03:24
Hi @bummoblizard , new user to Code app, very good by the way, any updates on the second editor for better touchscreen support that you mentioned last year?

**Comment by bummoblizard** [comment] 2024-04-29 08:45
In the latest TestFlight build, you might enable Runestone Editor under the experimental settings section for touch control support.

**Comment by D1reW0lf** [comment] 2024-04-29 08:57
To bad the TestFlight beta is full. 😕

**Comment by bummoblizard** [comment] 2024-04-29 09:01
@D1reW0lf I just opened up more slots :)

**Comment by D1reW0lf** [comment] 2024-04-29 10:35
> @D1reW0lf I just opened up more slots :)

Thank you so much!! 🖤
Will it, eventually, “color code” with Runestone?

**Comment by bummoblizard** [comment] 2024-04-29 13:20
Currently there is syntax highlighting for C, C++, JS and Python.

**Comment by D1reW0lf** [comment] 2024-04-29 18:07
> Currently there is syntax highlighting for C, C++, JS and Python.
 
That explains why I didn’t see it (I was testing with html, php, .env files, json).
Thank you for letting me know.

**Comment by bummoblizard** [comment] 2024-06-12 13:02
1.8.0 brings support for [Runestone](https://github.com/simonbs/Runestone) editor which allows native text selection. It can be toggled in the settings menu or in the quick menu.

<img width="311" alt="image" src="https://github.com/thebaselab/codeapp/assets/38398443/aa6dc2a1-dfa3-46ce-9e33-f09cd267f11c">

**Closed by bummoblizard** 2024-06-12 13:02 UTC
Labels: enhancement
