### ISSUE TITLE
Having troubles compiling XCode project

### ISSUE THREAD

**Issue by Ryorama** [thebaselab/codeapp#211] opened 2021-07-25 17:54 UTC
When I try to compile the project, I get different errors depending on which project file I open (.xcodeproject, .xcworkspace) which I can't figure out how to fix. For the .xcodeproject file, I get the error "There is no XCFramework found at 'WORKSPACE FOLDER ROOT/git.xcframework'". As for the .xcworkspace, I get the following error upon compiling...

ModuleSPM.swift: "Type 'Bundle' has no member 'module'".

I'm using the latest XCode version as well as MacOS version 11.1 "Big Sur". 

What I did to get to this issue:
1. Clone the repository to my pc
2. Execute the 'downloadFrameworks.sh' file
3. Open any workspace file
4. Change the bundle identifier as well as the provisioning profile
5. Attempt to compile and get errors

If I am doing anything wrong, please tell me so I can fix it.

**Comment by bummoblizard** [comment] 2021-07-25 18:36
`.xcworkspace` should be the file you open. For Git, please manually remove it from the project as I haven't uploaded the binary.

**Comment by Ryorama** [comment] 2021-07-25 18:50
Ah ok. Also, the swift error was happening because the Framework folder was somehow deleted.

**Comment by bummoblizard** [comment] 2021-07-25 19:02
Please checkout to the latest commit. Some resource files were missing when I uploaded the source code to GitHub.

**Comment by bummoblizard** [comment] 2021-07-25 19:05
And if you are on Xcode 12, you might need to replace SwiftGit2.framework with this because the included framework is built for Xcode 13.
[SwiftGit2.framework.zip](https://github.com/thebaselab/codeapp/files/6874428/SwiftGit2.framework.zip)

**Comment by Ryorama** [comment] 2021-07-25 19:23
Ok, I'll do that. Though, I'm getting this new error saying there's a duplicated Info.plist file somewhere when compiling. 

![image](https://user-images.githubusercontent.com/35707939/126910884-56e927de-391c-43f6-90ef-a852b075166b.png)

**Comment by bummoblizard** [comment] 2021-07-25 19:30
Try to clean the build folder with `Command-K`.

> Ok, I'll do that. Though, I'm getting this new error saying there's a duplicated Info.plist file somewhere when compiling.
> 
> ![image](https://user-images.githubusercontent.com/35707939/126910884-56e927de-391c-43f6-90ef-a852b075166b.png)

**Comment by Ryorama** [comment] 2021-07-25 19:31
Nope, still there

**Comment by bummoblizard** [comment] 2021-07-25 19:33
Try this: https://stackoverflow.com/questions/50718018/xcode-10-error-multiple-commands-produce/50719379#50719379

**Comment by Ryorama** [comment] 2021-07-25 19:35
I tried that, but then I get these errors

![image](https://user-images.githubusercontent.com/35707939/126911169-25426166-73c9-425c-bf17-81b54949462d.png)

**Comment by bummoblizard** [comment] 2021-07-25 19:40
The first error should be fixed in the latest commit. Can you check if `CodeApp/Framework/MarkdownView/Sources/MarkdownView/Resources` exists?

**Comment by Ryorama** [comment] 2021-07-25 19:42
Yep, it's there

![image](https://user-images.githubusercontent.com/35707939/126911366-e5a3f304-5d23-43b6-bf91-722c769a273e.png)

**Comment by bummoblizard** [comment] 2021-07-25 19:45
Ok. Open `CodeApp/Framework/MarkdownView` as a separate project. Don't open `.xcodeproj` and drag the folder to Xcode. Does it build?

![image](https://user-images.githubusercontent.com/38398443/126911453-ce17aa25-fa8d-4ca4-ad25-413afb65b078.png)

**Comment by Ryorama** [comment] 2021-07-25 19:50
Hmmm, hold on. The folder showed up in XCode, but not in my file system. I just copied it trough the file system this time and I am going to attempt to compile the project again.

**Comment by bummoblizard** [comment] 2021-07-25 20:20
I found out that there's more missing files. They are now in the latest commit.

**Comment by Ryorama** [comment] 2021-07-25 21:14
Ok, updated my code with the missing resources again. I also decided to update to the XCode beta as well. Though of course, I'm still getting errors upon compiling

![image](https://user-images.githubusercontent.com/35707939/126913686-e77010fb-3c43-413c-9584-f909a88697d6.png)

**Comment by bummoblizard** [comment] 2021-07-25 21:33
> Ok, updated my code with the missing resources again. I also decided to update to the XCode beta as well. Though of course, I'm still getting errors upon compiling
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/35707939/126913686-e77010fb-3c43-413c-9584-f909a88697d6.png)
> 
> 

This seems like an error related to the SwiftGit framework. I'm unsure what's going on though. Are you building for a real device instead of the simulator?

**Comment by Ryorama** [comment] 2021-07-25 21:52
I'm trying to build the app so I can get a .app file. Also, I'm using a VM of MacOS so I don't think architecture should be a problem.

**Comment by bummoblizard** [comment] 2021-07-25 22:12
I see. I just reproduced the same problem on my other machine. I'll see how I can make this work.

**Comment by bummoblizard** [comment] 2021-07-25 22:20
Add this to the Xcode project (under the Framework folder) and link it: https://github.com/light-tech/Clibgit2/releases/tag/v1.1.0

**Comment by Ryorama** [comment] 2021-07-25 22:32
Did that work for you? Because I'm still getting these errors

![image](https://user-images.githubusercontent.com/35707939/126915439-242c96ce-653a-4475-8746-ae5e74faba91.png)

**Comment by bummoblizard** [comment] 2021-07-25 22:37
> Did that work for you? Because I'm still getting these errors
> 
> ![image](https://user-images.githubusercontent.com/35707939/126915439-242c96ce-653a-4475-8746-ae5e74faba91.png)

It did work for me. But at least we are getting there as the first error is gone. Can you click on the first error and let me look at the details?

**Comment by Ryorama** [comment] 2021-07-25 22:39
> > Did that work for you? Because I'm still getting these errors
> > ![image](https://user-images.githubusercontent.com/35707939/126915439-242c96ce-653a-4475-8746-ae5e74faba91.png)
> 
> It did work for me. But at least we are getting there as the first error is gone. Can you click on the first error and let me look at the details?

![image](https://user-images.githubusercontent.com/35707939/126915588-0eb86693-b4e7-410c-bdeb-c8480e23321e.png)

![image](https://user-images.githubusercontent.com/35707939/126915599-43d5c419-c741-46cb-9747-d7e0568aea3c.png)

**Comment by bummoblizard** [comment] 2021-07-25 22:43
Click on the red button. What does it say?

**Comment by Ryorama** [comment] 2021-07-25 22:44
![image](https://user-images.githubusercontent.com/35707939/126915690-a37e3cc4-3106-48df-bd21-2eab90407016.png)

**Comment by bummoblizard** [comment] 2021-07-25 22:44
Also, make sure you opened the .xcworkspace file, not the .xcodeproj file.

**Comment by Ryorama** [comment] 2021-07-25 22:45
I did

**Comment by Ryorama** [comment] 2021-07-25 22:51
You mean this file right?

![image](https://user-images.githubusercontent.com/35707939/126915842-b9a1fec8-a339-423c-ba7a-88ceee0618c4.png)

**Comment by bummoblizard** [comment] 2021-07-25 23:02
Yes. Can you try to remove the existing Swift Package dependency on MarkdownView and use this instead? https://github.com/thebaselab/MarkdownView

It should look something like this: 
![image](https://user-images.githubusercontent.com/38398443/126916120-5a6139d9-7598-47a7-b2ae-a40bf651b439.png)

**Comment by Ryorama** [comment] 2021-07-25 23:11
Finally!!!! After an entire day it finally compiles!

**Comment by bummoblizard** [comment] 2021-07-25 23:14
Great! I'm sorry for the dependencies mess. Let me know if you need any other help.

**Comment by Ryorama** [comment] 2021-07-26 23:37
Hmmm, so finally got around to installing the IPA onto my device, but as soon as I open the app it crashes. Is there a way I can get a crash log or something? Because I have no idea what would cause the crash

**Comment by bummoblizard** [comment] 2021-07-27 00:04
You'll need to attach your device to a debugger. I think it would be more convenient if you use usb passthrough and connect your device to the vm directly.

For the second question, you can add the directory to `PATH`. Add this in the `init()` method in CodeApp.swift.
```swift
setenv("PATH", "PATH-TO-DIRECTORY" + ":" + String(utf8String: getenv("PATH"))!, 1)
```

**Comment by bummoblizard** [comment] 2021-07-27 00:08
You might also be able to find a crash log in the settings app. Go `Settings > Privacy > Analytics & Improvements > Analytics Data`.

**Comment by bummoblizard** [comment] 2021-07-27 15:42
> Hmmm, so finally got around to installing the IPA onto my device, but as soon as I open the app it crashes. Is there a way I can get a crash log or something? Because I have no idea what would cause the crash
> 
> 
> 
> Edit: Also, how do allow the terminal to look for commands in a new directory?

You might also want to add `java` and `javac` in commandDictionary.plots.

**Comment by Ryorama** [comment] 2021-07-27 17:22
> > Hmmm, so finally got around to installing the IPA onto my device, but as soon as I open the app it crashes. Is there a way I can get a crash log or something? Because I have no idea what would cause the crash
> > Edit: Also, how do allow the terminal to look for commands in a new directory?
> 
> You might also want to add `java` and `javac` in commandDictionary.plist.

I was wondering about that. How does the formatting work for it though? Because from what I'm seeing it's built to be used with the downloaded .xcframework files

**Comment by Ryorama** [comment] 2021-07-27 17:23
> You might also be able to find a crash log in the settings app. Go `Settings > Privacy > Analytics & Improvements > Analytics Data`.

Also, I did manage to pull out my dads old slow mac and get XCode running on it. Along with that, I used the console app to access my phones logs so I could see the issues that occur when running the app.

**Comment by Ryorama** [comment] 2021-07-27 17:35
Bootstrapping failed for <FBApplicationProcess: 0x15b9794c0; application<com.ryorama.vscode>:<invalid>> with error: <NSError: 0x2813499b0; domain RBRequestErrorDomain; code 5; reason "Launch Failed."> {
   underlyingError = <NSError: 0x2813513e0; domain NSPOSIXErrorDomain; code 85>;
}

**Comment by Ryorama** [comment] 2021-07-27 17:37
I also just found this on the apple developer website: https://developer.apple.com/documentation/foundation/nsposixerrordomain

**Comment by Ryorama** [comment] 2021-07-27 18:59
Ok, well... I figured out why it's crashing, and because I don't have a paid developer account I may never be able to compile and run the app from my end

![image](https://user-images.githubusercontent.com/35707939/127212218-bbb08d76-2e46-4f93-9004-73e945e8ab39.png)

**Comment by bummoblizard** [comment] 2021-07-27 20:52
I don't think it's necessary though. Can you try to remove any reference to app group in both `Code` and `extension` target?

**Comment by Ryorama** [comment] 2021-07-27 20:54
That's what I did, but the app still tries to access them which is why it crashes

**Comment by bummoblizard** [comment] 2021-07-27 20:55
> > > Hmmm, so finally got around to installing the IPA onto my device, but as soon as I open the app it crashes. Is there a way I can get a crash log or something? Because I have no idea what would cause the crash
> 
> > > Edit: Also, how do allow the terminal to look for commands in a new directory?
> 
> > 
> 
> > You might also want to add `java` and `javac` in commandDictionary.plist.
> 
> 
> 
> I was wondering about that. How does the formatting work for it though? Because from what I'm seeing it's built to be used with the downloaded .xcframework files

How was the Java built? Is the result binary an executable or a shared library? You'll want a shared library and bundle it into a xcframework.

**Comment by Ryorama** [comment] 2021-07-27 20:57
> > > > Hmmm, so finally got around to installing the IPA onto my device, but as soon as I open the app it crashes. Is there a way I can get a crash log or something? Because I have no idea what would cause the crash
> > 
> > 
> > > > Edit: Also, how do allow the terminal to look for commands in a new directory?
> > 
> > 
> > > 
> > 
> > 
> > > You might also want to add `java` and `javac` in commandDictionary.plist.
> > 
> > 
> > I was wondering about that. How does the formatting work for it though? Because from what I'm seeing it's built to be used with the downloaded .xcframework files
> 
> How was the Java built? Is the result binary an executable or a shared library? You'll want a shared library and bundle it into a xcframework.

I'm not sure if that would be possible with the way it was made. The code can be found here if you want to check it out though: https://github.com/PojavLauncherTeam/android-openjdk-build-multiarch

**Comment by Ryorama** [comment] 2021-07-27 20:57
> I don't think it's necessary though. Can you try to remove any reference to app group in both `Code` and `extension` target?

The error is being caused from lines of code like this "let sharedURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.ryorama.vscode")!"

**Comment by bummoblizard** [comment] 2021-07-27 21:00
> > I don't think it's necessary though. Can you try to remove any reference to app group in both `Code` and `extension` target?
> 
> 
> 
> The error is being caused from lines of code like this "let sharedURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.com.ryorama.vscode")!"

I see. Remove all lines inside the refreshNodeCommand method should do then.

**Comment by Ryorama** [comment] 2021-07-27 21:03
Ok, but that line was from the init method in the Codeapp.swift file, so should I remove all stuff related to that as well?

**Comment by bummoblizard** [comment] 2021-07-27 21:09
Oh yes I think so.

**Comment by bummoblizard** [comment] 2022-05-03 02:15
I revamped the build process now. You should be able to build the project following the commands in README.md now.

**Closed** 2022-05-03 02:16 UTC
