### ISSUE TITLE
Support for Azure DevOps Repos

### ISSUE THREAD

**Issue by ChrisTav424** [thebaselab/codeapp#118] opened 2021-05-18 08:40 UTC
This app looks like exactly what I'm after but I'm currently using Azure DevOps Repos rather than GitHub. Are there any plans to support these? 

![1B1091E4-E0A0-434B-9FB9-9A5B3DFEAAA6](https://user-images.githubusercontent.com/44398463/118620323-4d637e00-b7bd-11eb-9647-d807166810d9.jpeg)

**Comment by bummoblizard** [comment] 2021-05-18 08:44
The app should support any git server. Did you add your credentials in settings page? It can be done by `Settings > Version Control > Authentication`.

**Comment by ChrisTav424** [comment] 2021-05-18 08:52
I hadn't found the authentication option in settings when I posted this. I now get the following after using credentials

![1CD13175-F732-44EF-91CA-2034C2323C3A](https://user-images.githubusercontent.com/44398463/118621961-c6170a00-b7be-11eb-98c1-c254e23a64c9.png)

I also created a public repo in Azure DevOps for testing :)

https://ctav@dev.azure.com/ctav/test-public/_git/test-public

**Comment by bummoblizard** [comment] 2021-05-18 09:05
Confirmed and thanks for the report! I am working on a fix.

**Comment by ChrisTav424** [comment] 2021-05-18 09:06
Blimey, that's some impressive support! 

Thank you @bummoblizard!

**Comment by bummoblizard** [comment] 2021-05-18 09:28
Fix committed: https://github.com/thebaselab/codeapp-source/commit/e46959085a604598af5fb25457a62440dd9fd26a

**Closed by bummoblizard** 2021-05-18 09:28 UTC
Labels: bug, question

**Comment by bummoblizard** [comment] 2021-06-03 19:11
Hey @ChrisTav424. This should be fixed in the latest TestFlight build: https://testflight.apple.com/join/EgZ8sE2P

**Comment by ChrisTav424** [comment] 2021-06-03 20:16
Just tested, works perfectly! Thank you for fixing it so quickly :) 

Can I ask what was wrong? Just interested in how Azure DevOps differs from GitHub :)

**Comment by bummoblizard** [comment] 2021-06-04 06:50
> Just tested, works perfectly! Thank you for fixing it so quickly :)
> 
> Can I ask what was wrong? Just interested in how Azure DevOps differs from GitHub :)

When cloning from GitHub, a suffix `.git` is needed at the end of the url. For example: `https://github.com/thebaselab/codeapp.git`

To mimic the behaviour of cli git, which allows cloning using `https://github.com/thebaselab/codeapp`, `.git` is appended to the end of the repository url. It turns out that this is not standardised and will fail on Azure Devops. So I removed this logic.

**Comment by ChrisTav424** [comment] 2021-06-04 07:35
Ah that makes sense, thanks for sharing :)
