### ISSUE TITLE
Feature Request: SSH Improvements

### ISSUE THREAD

**Issue by RobertCordingly** [thebaselab/codeapp#76] opened 2021-04-04 04:49 UTC
This app would be AMAZING if it had better SSH/Remote connections support. If you could mimic VS Code's remote connections plugin this would be great. 

Beyond that minor SSH improvements would be awesome, for example pressing tab to auto complete and adding arrow keys on the keyboard to go up/down.

**Comment by EliotHertenstein** [comment] 2021-04-17 23:16
This or SFTP would work really great! Sftp especially would be nice :)

**Comment by AaronHeee** [comment] 2021-06-10 03:42
Agreeeee!. [Remote-SSH](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) like VS Code would be a killer feature for codeapp.

**Comment by mcx808** [comment] 2021-06-28 17:45
Throwing my hat into the ring for this feature. 
With Remote-SSH development I could work completely from the iPad when travelling.

**Comment by bummoblizard** [comment] 2021-06-29 10:15
Thank you for all your feedback! I will make this a priority and see if I can include it in July's update.

**Comment by sylvoie** [comment] 2022-01-22 15:40
Hello,

If it’s not too late, can you add a me too. My wish is to be able to run code remotely to run docker-compose and provision a stack of servers in Docker. Or run remotely Ansible!

I want to tell you that your application has given me hope.  I see that it is now possible to use my iPad Pro as a developer tool.  You have to continue your excellent work.

Thank you.

**Comment by bummoblizard** [comment] 2022-05-03 02:18
SFTP is available in the TestFlight builds now. I am now working on terminal support.

**Comment by mcx808** [comment] 2022-05-03 11:16
> SFTP is available in the TestFlight builds now. I am now working on terminal support.

Any chance I can get an invite to testflight?

**Comment by mcx808** [comment] 2022-05-03 14:21
So it is, thanks! I can confirm remote access via SFTP is working for me. Looking forward to remote terminal access.

FYI, I've also started using another interesting iPad app: [Blink Shell](https://blink.sh).
It supports local vscode environment & remote vscode development via ssh, although this method doesn't yet support remote terminal either.

**Comment by mcx808** [comment] 2022-05-03 14:42
> > So it is, thanks! I can confirm remote access via SFTP is working for me. Looking forward to remote terminal access.
> > FYI, I've also started using another interesting iPad app: [Blink Shell](https://blink.sh).
> > It supports local vscode environment & remote vscode development via ssh, although this method doesn't yet support remote terminal either.
> 
> Wow it's amazing! It's a clever approach I must say. Does it also work offline?

Kind of, you can still start a code instance locally (on the iPad) without a network connection, but then you can only edit files that are within that instance. It has a files.app provider so remote hosts can be browsed within iOS files, but it doesn't seem to work with local files. It works best for remote development either on a server or github repos.

**Comment by Prometheia** [comment] 2022-06-02 21:33
Just to be clear on the terminology, you have SFTP setup under the Remote Connections menu, and you’re working on terminal connections next. Does that refer to SSH connections?

**Comment by bummoblizard** [comment] 2022-06-03 01:51
> Just to be clear on the terminology, you have SFTP setup under the Remote Connections menu, and you’re working on terminal connections next. Does that refer to SSH connections?

Yes. Because SFTP and SSH are basically the same protocol.

**Comment by bummoblizard** [comment] 2022-06-03 03:14
> Right, but is that the reason that straight SSH connections don’t currently work? Because you’re still working on it (and not because there’s a bug or user error)? If I understand correctly, SFTP uses SSH for authentication, but SSH itself needs to be implemented differently. Currently, in the Remote Connections menu, if I plug in my remote server’s IP address, port 22, username, and password, I get a ‘unknown error’ message. I know for sure that SSH on the remote server is setup correctly because I can access it from other apps.

I'm still working on it.

**Comment by Prometheia** [comment] 2022-06-03 03:50
> > Right, but is that the reason that straight SSH connections don’t currently work? Because you’re still working on it (and not because there’s a bug or user error)? If I understand correctly, SFTP uses SSH for authentication, but SSH itself needs to be implemented differently. Currently, in the Remote Connections menu, if I plug in my remote server’s IP address, port 22, username, and password, I get a ‘unknown error’ message. I know for sure that SSH on the remote server is setup correctly because I can access it from other apps.
> 
> I'm still working on it.

Great! Really looking forward to having this feature! I use Juno Connect for data science on my iPad connected to my remote server. Your app will pair nicely if I can connect to that same server in a VSCode environment. Keep up the great work!

**Comment by bummoblizard** [comment] 2022-06-04 07:41
Guys I've managed to make it work. Hopefully I can put this on TestFlight within this weekend.

![Simulator Screen Shot - iPad (9th generation) - 2022-06-04 at 15 40 13](https://user-images.githubusercontent.com/38398443/171989821-65eb6819-bf33-4cfd-a7db-1e129db073f3.png)

**Comment by Prometheia** [comment] 2022-06-05 15:57
I have the latest TestFlight build and am still having trouble connecting. 

I tried two methods.

Local network:
- Address: IP address of PC I want to connect to
- Port: 22
- Username: username of PC
- Password: username of PC

This method either results in a crash to the home screen or the ‘unknown error’ in the app.

Alternative method: Ngrok
I also have ngrok running on the PC I want to connect to. This forwards traffic from ngrok to port 22 on the PC I want to connect to.
- Address: 1.tcp.ngrok.io
- Port: my reserved ngrok tcp address port
- Username: username of PC
- Password: password of PC

This method also either results in a crash to the home screen or the ‘unknown error’ in the app.

**Comment by Prometheia** [comment] 2022-06-05 16:03
I also tried connecting to a Linux server I have running and that connected successfully. I’m going to check to see if I have any firewall settings on the Windows PC that would be blocking the connection.

Do you know of anything on your side that would prevent connections on Windows PCs but not Linux?

**Comment by bummoblizard** [comment] 2022-06-05 16:11
> I also tried connecting to a Linux server I have running and that connected successfully. I’m going to check to see if I have any firewall settings on the Windows PC that would be blocking the connection.
> 
> Do you know of anything on your side that would prevent connections on Windows PCs but not Linux?

I have one in mind. But I'll test it on a Windows device and let you know.

**Comment by Prometheia** [comment] 2022-06-05 16:16
I also seem to be missing the ‘Run’ button that’s normally in the upper right:
![IMG_1771](https://user-images.githubusercontent.com/49218326/172060097-44caefce-f9d3-493d-aca2-5dc81a165ae9.png)

**Comment by bummoblizard** [comment] 2022-06-05 16:26
> I also seem to be missing the ‘Run’ button that’s normally in the upper right:
> ![IMG_1771](https://user-images.githubusercontent.com/49218326/172060097-44caefce-f9d3-493d-aca2-5dc81a165ae9.png)

It's currently an expected behaviour. You can still run your code in the terminal by running the python command.

**Comment by bummoblizard** [comment] 2022-06-08 02:06
> I also tried connecting to a Linux server I have running and that connected successfully. I’m going to check to see if I have any firewall settings on the Windows PC that would be blocking the connection.
> 
> 
> 
> Do you know of anything on your side that would prevent connections on Windows PCs but not Linux?

Hi. Please see if build 91 on TestFlight resolves this.

**Comment by Prometheia** [comment] 2022-06-08 02:28
> Hi. Please see if build 91 on TestFlight resolves this.

Downloaded and tested build 91.

A couple things:

- App crashes the first time I add any new remote connection. Subsequent attempts appear to be successful.
- It seems like it can connect to my Win10 PC because the terminal displays my username/PC name. However, the connection isn’t saved to the list of remotes, and I can’t access any files for editing. ‘Unknown error’ still pops up.
- The terminal also opens with ‘clear’ already typed out (see image).

![IMG_1807](https://user-images.githubusercontent.com/49218326/172518104-4a099258-4934-4838-bf40-c0bdb8b07ead.jpeg)

**Comment by Prometheia** [comment] 2022-06-08 03:55
Actually, I don’t think it’s connecting to the Win10 computer after all. There’s no indicator in the bottom-left that says I’m connected to a remote server. And Code never actually says ‘Connected to xxx.xxx.xxx.xxx’ ‘Fingerprint: ‘.

**Comment by bummoblizard** [comment] 2022-06-08 03:57
> Actually, I don’t think it’s connecting to the Win10 computer after all. There’s no indicator in the bottom-left that says I’m connected to a remote server. And Code never actually says ‘Connected to xxx.xxx.xxx.xxx’ ‘Fingerprint: ‘.

Right. Thanks for letting me know. I think I can get my hands on a Windows computer this week and fix it today.

**Comment by bummoblizard** [comment] 2022-06-11 08:57
> Actually, I don’t think it’s connecting to the Win10 computer after all. There’s no indicator in the bottom-left that says I’m connected to a remote server. And Code never actually says ‘Connected to xxx.xxx.xxx.xxx’ ‘Fingerprint: ‘.
> 
> The screenshot of the terminal above seems like it’s trying to connect, but quitting after some immediate point. I can’t type anything after ‘clear’ and hitting enter bumps me out of any quasi-remote connection (i.e. it sends me back to a local terminal).

It should be fixed in the latest commit. TestFlight build will be available soon.

**Comment by Prometheia** [comment] 2022-06-11 20:53
> It should be fixed in the latest commit. TestFlight build will be available soon.

Success! I can connect to my Windows server both over my local network and via my ngrok instance. Nice work!

There does seem to be sporadic crashing when connecting while the ‘Remember credentials’ option is selected. It’ll crash, and then the next time I connect with the option selected it’ll go through. Each subsequent connection is successful after that too.

**Comment by bummoblizard** [comment] 2022-06-12 03:17
> There does seem to be sporadic crashing when connecting while the ‘Remember credentials’ option is selected. It’ll crash, and then the next time I connect with the option selected it’ll go through. Each subsequent connection is successful after that too.

Interesting. I'll make sure it's fixed before it's released on the App Store. Thanks!

**Closed** 2023-02-16 09:22 UTC
Labels: enhancement, priority

**Comment by Kabongosalomon** [comment] 2023-03-10 11:47
Hi @bummoblizard, thanks for the great work on the app.

I would like to know if ssh through a jump server is already supported. 

E.g.ssh -i .ssh/id_rsa -o ProxyCommand="ssh -W %h:%p user@jump.example.com -i .ssh/id_rsa" user@my-server


If not, is this possible/feasible?

**Comment by bummoblizard** [comment] 2023-03-10 15:26
> Hi @bummoblizard, thanks for the great work on the app.
> 
> 
> 
> I would like to know if ssh through a jump server is already supported. 
> 
> 
> 
> E.g.ssh -i .ssh/id_rsa -o ProxyCommand="ssh -W %h:%p user@jump.example.com -i .ssh/id_rsa" user@my-server
> 
> 
> 
> 
> 
> If not, is this possible/feasible?

It is possible, but not yet implemented. It's definitely something worth looking into.
