### ISSUE TITLE
Yarn (Package Manger)

### ISSUE THREAD

**Issue by OlshaMB** [thebaselab/codeapp#477] opened 2022-06-05 08:33 UTC
I'm trying to install yarn throw this command `npm install -g yarn` npm throws an error - EPERM that means operation not permitted and that i need root permissions, but there is no `su/sudo/doas`.

![image](https://user-images.githubusercontent.com/68439653/172042765-f3c67f99-644b-470e-a2c0-99ed55b4e69f.jpeg)

![image](https://user-images.githubusercontent.com/68439653/172042751-74c9f093-6af1-4774-88bb-7f330cc6182c.jpeg)

**Comment by OlshaMB** [comment] 2022-06-05 08:52
I saw the angular issue#476 and the same thing. Npm `-g`/`--global` option doesn't work, because this command needs `sudo` but `sudo` doesn't exist.

**Comment by bummoblizard** [comment] 2022-06-05 09:42
Yarn tried to spawn a subprocess while installing which is not allowed in iOS. Unfortunately this behaviour is unlikely to change anytime soon and there's little I can do to workaround it.

**Comment by OlshaMB** [comment] 2022-06-05 09:52
can i somehow install yarn other way?

**Comment by OlshaMB** [comment] 2022-06-05 10:11
I suggest adding custom package manager. For people to install commands like `yarn`, `make`, `coreutils` and other.
I will create separate issue for this #478

**Comment by bummoblizard** [comment] 2022-06-05 10:15
> can i somehow install yarn other way?

I hope I can find a way but I haven't managed to do it. Closing as duplicate of #172

**Closed by bummoblizard** 2022-06-05 10:15 UTC
