### ISSUE TITLE
Checking out work branch issues

### ISSUE THREAD

**Issue by allie-chan** [thebaselab/codeapp#896] opened 2023-08-14 01:43 UTC
First of all, thanks for making the app. 

I am on IpadPro11 2021. I have entered my github credentials (Personal Access Token) in the settings page and have successfully cloned a repo into the code-space. 

The Personal Access Token has all the rights and should be able to navigate through branches. 

However, I did not find a branch icon in the UI for me to switch between branches. 

I am currently running V1.4.5
![IMG-0641](https://github.com/thebaselab/codeapp/assets/76210740/12ffdd61-2928-4c4b-9d3b-da3af4f35e42)

Would appreciate if there are any clue or settings help

**Comment by bummoblizard** [comment] 2023-08-14 01:45
Hi. For the git controls to show up in the UI, the cloned repository must be at the root of the workspace. You can do this by holding the folder icon and select `Assign as workspace folder`.

**Comment by Allie-C** [comment] 2023-08-14 01:48
Got it, Thanks.
Will close this issue.

**Comment by Allie-C** [comment] 2023-08-14 05:04
does clicking `fetch` under `source control` panel directly acts like normal command `git fetch origin` ?       
I have opened a new branch on the repo on pc and `fetch` does not work to list my new repo in the branch icon

**Comment by bummoblizard** [comment] 2023-08-14 05:13
> does clicking `fetch` under `source control` panel directly acts like normal command `git fetch origin` ?
> I have opened a new branch on the repo on pc and `fetch` does not work to list my new repo in the branch icon

Yes. This might be caused by a synchronisation bug where the branch doesn't immediately show up in the menu. If you tap on the refresh button in the explorer, it should show up again.

Currently we are working on git related improvements, they will be available in the next update.

**Comment by bummoblizard** [comment] 2023-08-21 06:04
Fixed in https://github.com/thebaselab/codeapp/commit/b9b3e1933e4640c58367583e804d10577faff41b.

**Closed by bummoblizard** 2023-08-21 06:04 UTC
Labels: bug, question
